// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arch() {
  return window['go']['system']['Info']['Arch']();
}

export function ArchIs32Bit() {
  return window['go']['system']['Info']['ArchIs32Bit']();
}

export function ArchIs386() {
  return window['go']['system']['Info']['ArchIs386']();
}

export function ArchIs64Bit() {
  return window['go']['system']['Info']['ArchIs64Bit']();
}

export function ArchIsAmd64() {
  return window['go']['system']['Info']['ArchIsAmd64']();
}

export function ArchIsArm() {
  return window['go']['system']['Info']['ArchIsArm']();
}

export function ArchIsArm64() {
  return window['go']['system']['Info']['ArchIsArm64']();
}

export function Platform() {
  return window['go']['system']['Info']['Platform']();
}

export function PlatformIs(arg1) {
  return window['go']['system']['Info']['PlatformIs'](arg1);
}

export function PlatformIsDarwin() {
  return window['go']['system']['Info']['PlatformIsDarwin']();
}

export function PlatformIsLinux() {
  return window['go']['system']['Info']['PlatformIsLinux']();
}

export function PlatformIsWindows() {
  return window['go']['system']['Info']['PlatformIsWindows']();
}
