// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arch():Promise<string>;

export function ArchIs32Bit():Promise<boolean>;

export function ArchIs386():Promise<boolean>;

export function ArchIs64Bit():Promise<boolean>;

export function ArchIsAmd64():Promise<boolean>;

export function ArchIsArm():Promise<boolean>;

export function ArchIsArm64():Promise<boolean>;

export function Platform():Promise<string>;

export function PlatformIs(arg1:string):Promise<boolean>;

export function PlatformIsDarwin():Promise<boolean>;

export function PlatformIsLinux():Promise<boolean>;

export function PlatformIsWindows():Promise<boolean>;
