// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CpuName() {
  return window['go']['system']['System']['CpuName']();
}

export function CpuTotalLoad() {
  return window['go']['system']['System']['CpuTotalLoad']();
}
