// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CpuName():Promise<string>;

export function CpuTotalLoad():Promise<number>;
