// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['config']['Provider']['Get']();
}

export function LoadDefault() {
  return window['go']['config']['Provider']['LoadDefault']();
}
