// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logger} from '../models';

export function Debug(arg1:string):Promise<void>;

export function Error(arg1:string):Promise<void>;

export function Fatal(arg1:string):Promise<void>;

export function Info(arg1:string):Promise<void>;

export function Pointer():Promise<logger.Logger>;

export function Print(arg1:string):Promise<void>;

export function Trace(arg1:string):Promise<void>;

export function Warning(arg1:string):Promise<void>;

export function WithField(arg1:string,arg2:any):Promise<logger.Logger>;

export function WithLevel(arg1:logger.Level):Promise<logger.Logger>;

export function WithMiddleware(arg1:any):Promise<logger.Logger>;

export function WithName(arg1:string):Promise<logger.Logger>;

export function WithOutput(arg1:string):Promise<logger.Logger>;
