// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1) {
  return window['go']['logger']['Logger']['Debug'](arg1);
}

export function Error(arg1) {
  return window['go']['logger']['Logger']['Error'](arg1);
}

export function Fatal(arg1) {
  return window['go']['logger']['Logger']['Fatal'](arg1);
}

export function Info(arg1) {
  return window['go']['logger']['Logger']['Info'](arg1);
}

export function Pointer() {
  return window['go']['logger']['Logger']['Pointer']();
}

export function Print(arg1) {
  return window['go']['logger']['Logger']['Print'](arg1);
}

export function Trace(arg1) {
  return window['go']['logger']['Logger']['Trace'](arg1);
}

export function Warning(arg1) {
  return window['go']['logger']['Logger']['Warning'](arg1);
}

export function WithField(arg1, arg2) {
  return window['go']['logger']['Logger']['WithField'](arg1, arg2);
}

export function WithLevel(arg1) {
  return window['go']['logger']['Logger']['WithLevel'](arg1);
}

export function WithMiddleware(arg1) {
  return window['go']['logger']['Logger']['WithMiddleware'](arg1);
}

export function WithName(arg1) {
  return window['go']['logger']['Logger']['WithName'](arg1);
}

export function WithOutput(arg1) {
  return window['go']['logger']['Logger']['WithOutput'](arg1);
}
