# Unique app ID to prevent launching this app twice
id: mncplay
# Debug features
debug:
  # Open browser's DevTool alongside with the app
  inspector: true
  # Logger options
  log:
    # Log level
    level: debug
    # If specified - copy logs to files by template.
    # You can use .stamp (unix timestamp), .home (user's home dir), .user (current username)
    # .year, .month, .day, .hour, .minute, .second
    output: ./logs/{{.year}}{{.month}}{{.day}}_{{.hour}}{{.minute}}{{.second}}.log
# Window decoration and functionality options
window:
  # Controls how the window header looks
  header:
    # Use native OS window frame (some appearance features won't work)
    native: false
    # Window title
    title: MNC.RED Play
    # Display maximise button (won't work with native)
    maximise: false
    # Header background style
    background:
      color: "#00000020"
    # Title text color
    text:
      color: "#000000FF"
  # Window default height and maximum and minimum sizes
  # Set max or min to 0 for unlimited/unrestricted
  width:
    default: 1000
    min: 1000
    max: 1000
  # Window default height and maximum and minimum sizes
  # Set max or min to 0 for unlimited/unrestricted
  height:
    default: 600
    min: 600
    max: 600
  # Allow window resizing
  resizable: false
  # Window's design
  appearance:
    # Window corner roundness. Works only for Windows and MacOS. It won't work with .window.header.native
    # Set to 0 for square corners or any value in pixels
    roundness: 8
    background:
      color: "#FFFFFFFF"
