// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1) {
  return window['go']['logrus']['Logger']['Debug'](arg1);
}

export function Error(arg1) {
  return window['go']['logrus']['Logger']['Error'](arg1);
}

export function Fatal(arg1) {
  return window['go']['logrus']['Logger']['Fatal'](arg1);
}

export function Info(arg1) {
  return window['go']['logrus']['Logger']['Info'](arg1);
}

export function Print(arg1) {
  return window['go']['logrus']['Logger']['Print'](arg1);
}

export function Trace(arg1) {
  return window['go']['logrus']['Logger']['Trace'](arg1);
}

export function Warning(arg1) {
  return window['go']['logrus']['Logger']['Warning'](arg1);
}
