// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1:string):Promise<void>;

export function Error(arg1:string):Promise<void>;

export function Fatal(arg1:string):Promise<void>;

export function Info(arg1:string):Promise<void>;

export function Print(arg1:string):Promise<void>;

export function Trace(arg1:string):Promise<void>;

export function Warning(arg1:string):Promise<void>;
